language: android

android:
   components:
   - tools
   - platform-tools
   - android-25
   - build-tools-25.0.0
   - extra

jdk: oraclejdk8

notifications:
  email: false

before_install:
   - touch local.properties
   - source .travis/env.sh
   - openssl aes-256-cbc -K $encrypted_d6b6b9994385_key -iv $encrypted_d6b6b9994385_iv -in release.jks.enc -out release.jks -d

script:
  - ./gradlew clean assembleDebug
  - cp app/build/outputs/apk/MoeGallery-$GIT_TAG-debug.apk $HOME
  - ./gradlew clean assembleRelease
  - cp app/build/outputs/apk/MoeGallery-$GIT_TAG-release.apk $HOME
  - md5sum "$HOME/MoeGallery-$GIT_TAG-debug.apk"
  - md5sum "$HOME/MoeGallery-$GIT_TAG-release.apk"
  - sha1sum "$HOME/MoeGallery-$GIT_TAG-debug.apk"
  - sha1sum "$HOME/MoeGallery-$GIT_TAG-release.apk"

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file:
    - "$HOME/MoeGallery-$GIT_TAG-debug.apk"
    - "$HOME/MoeGallery-$GIT_TAG-release.apk"
  skip_cleanup: true
  on:
    tags: true
    
env:
  global:
    # GITHUB_TOKEN
    - secure: "Ikv4i2ZNhsp4dvqaQiG3QlFa/eIQjO9KnBplRtNbfNQLZ4I9tu6ogKp+oDVk0QbvexTXLThYLaGTHqzacxW69HtrVMV/zif9sH11WNZQY1eBn/oZiSHLryY58wjOepI7xSsbCWIWzo/4FW8RwA6fwhlW3na2HA96mvHwrVLpC9sgSfT9rmt+80nXR0kGPexJJ77UKnZqU9JvjLn65FIFbHsCo5HyaBCUgb3HEtwZP6O0+CvwGrsRw1zvr0Vzn+Epqi3jxo0yfOg+waqsLCujCFSgGvQheTpGpQfFOw8emM/nR0nkTFhmbk4+D6T5Yb66RUyFn+/rpl3a+nVOHF9efQugbLPNuIEIXit4O9DZiwMpRXllNay0dBjJHbsjBTePXgBPTTYjwSAitIVSUmgxYYlsKOUUEovTaBmodHYOQT0EPNDf6UJW2QzjObtIAG9YJZgTkCC9Ubhct0geLoJwKP82g2KZsuMthKjYVlvrMI2RfeznBJvuSdpMKzsQYdPvRiT7DK9rNotzAKM4sFL9Wk68lhfWb5RJW02TOxAZ/cZIdsoCZmBmqittasGvXYDBsf1tfGmYlWZVYAzBmy1yeAY8sqXTst6AERiYn9tCJQhw5vGRXdIuhuDJtlki7uBrmWkr/6AThbyxLg2T294Fe3ByGj1RwM7bODmf7pQhS5Y="
    # KEYSTORE_PASSWORD
    - secure: "yrgCs40FfTr1vr1BhIPKyY+Y0/Ir5Vrj7YjQh7Lnmh9c4XKA89QYGU+oF17poHF+zv5B83uzkItz8TL4/KK6xwP8T5mB4hWaQNr4IZnZ2lDV3V/DsMuslglDQybMT3fRqDl7ywFyovKofO/uxdA3COLFKpu0oQnQ44q5LlLKHfIJitHqmh35vJl55nIyu7O+jPIunyO9Tp8NPoSquIyKDY1fS6xaIuiFv67Dy0b5Yihrp+yBMu9YZFkTJxvQUd5Oj6Zsl0SBnj9Qy/RGMllRhLlmcwS3uyi0fSvOXx4wePkA3zvjRBGlK8GRYCBhtR8eMOSowJopTuuyVul92J20S5CW+iptylMn+rwpbCV4AGgD+UepcNO7UBG/M42b05Uet224yif5Mj5LZhC0Tu6ATdSi8adbwauAQsDJu68fCDpL3TGIXrY42h/Bz6CaLwKmduka/HDSbZn+z0NYmkqnShIBUkDFvDTiD4W7XMIqyi7O1JQebdId/DfHQA+4f5Fy+Bgj8ynI3gytC8Dj6M1kCfPxVdi8xU8iIO6HvDLO+3dR2m+XXcVOoD5IAxaBDrtfhM+q+M7T3hx+fQzEpybZ3nD0t9eO6NKYCu346t4H0uaWMphFPDNhz2mUexrP8KJ0do2xE39uP2TsOFnBM2H74YAO8PNPQXuW59Xa3KX5On0="
    # ALIAS_PASSWORD
    - secure: "OR6o2j62BJKmt/kI/1+N8HgYIx9+owhrkbveEzbXOkRkrRaDUPUX+JRh7OWQZ2of5duknaaKPzYBw4XaUIFkpFaFTUD5ppgAB+Nl22PF9RcB6VesRTpjDb09G3K20avXg21FPu7aNYxWixYj4vIBJj9ktMgB8i/9CDdPX/9OoY/Y+b/473w0BnBL8jYZZwGyJRW130xp0DMMVdsrg8ZMwXbLIbZvdzH4GXJmYUTT1mFxuP31QsNzX2MCSUpNfiUl4mBkc+8ose3RLdEFgfq03jfL01RRYxmc2CTQl7vKXUwPRZtfgws5YwRqO+Cid4SrBzHExIbz4HYYNGXcg/b62B2OKhfXbN/SyhhjdT6UPuAMg+xImCK6k69fZzzb8C2zy7oi4/xyMGT20YBHEmeJ7UD4zG9nRDZq6K4lXqwkbqh6oxOXSkBNwonQfEMCeB03u2g3xaDJT4wWPcB0RJ4U5e5UBYVGs6wPQPxOK1B3IEYUTGLGfkVuTggeOXlBzuYuAGCcAIKcB3P5gin+m9qzMPszcLGpXBcEnDjLXwSCza7kgTI4HivNGhnX+Wtod21AJb6acU09ld+1jB4M4BhhdwfSGp0Z57B25vP+gFCoCaG3Ffz4PlMoS/dph9W9v3/589aaZm0uB1kraQDQPRg5eazRkS11WMgLGxtjjuDjGOg="
    # ALIAS
    - secure: "qUUGoLn/R9qKq2U1s0AqCdZp0wqGs5A9cYl2zEyCadAOKnNtBJWyl0IYfBuSA4NV6Ah6FkZY0bA2aw/jVG30wRTBYFPaH9xvEbuBanUJjIykHOYl4MJppfUkBSKwVyPmn5Vp+sMCJRCkHxtmhv9HKusEyPGGqVN2zbeoziHYKkNZzhR1nOae6+i4nMWpQ3Z2zVpzZ2ZH3hcq49nhYnnPdiytKxJVjJhAUd2OOEg62KcJpmKkkn69zjit3yiGNad1efHwL7SxTp72IjzZsW+EjOop7gDn0gILZj7WO9fqyQ8zvLl0ze8GrjKuXyY1AKhnYGxNbuuXkhQD494XCEFrL0hqyQA9475laz6kfSSPop7PsoSHotDMVzQ80yFmW3d25NiMxbs5OFQcNwKJnkyvuMYmM8OuqTX1f0vXbQH5ttgzfAqzFbEHBr71Ct9FKumNcITJwc0wUCiAWjoD/YMdESKXhC2rmp52BKPCENcFPh5SJvAqZcOM0FO0kk9NHEDpll0Ql1+xU+j/V29Fg8+R/jwiwopkImvr+Z9mtcJ94yOFe3bz2RirH3VBP4foQt1M/qoGY6WCMWNra0mrL7X001U41bSo/dKoQtaWGkFUQrHwEquGbeuVAQMPowBym2to+A43qFSaL0wKw/cwNoBAVN86eWJbuaWNoiWPne7yki8="
